export class   categoriesData
{
   categories =[
        {
            "id":"1",
            "name":"category1",
            "products":[
                {
                    "id":"1",
                    "code":"123",
                    "name":"product1",
                    "price":"123"
                },
                {
                    "id":"2",
                    "code":"234",
                    "name":"product2",
                    "price":"234"
                },
                {
                    "id":"3",
                    "code":"345",
                    "name":"product2",
                    "price":"234"
                }
            ]
        },
        {
            "id":"2",
            "name":"category2",
            "subCategoryOf":"category1",
            "products":[
                {
                    "id":"1",
                    "code":"123",
                    "name":"product1",
                    "price":"123"
                },
                {
                    "id":"2",
                    "code":"234",
                    "name":"product2",
                    "price":"234"
                },
                {
                    "id":"3",
                    "code":"345",
                    "name":"product2",
                    "price":"234"
                }
            ]
        },
        {
            "id":"3",
            "name":"category3",
            "products":[
                {
                    "id":"1",
                    "code":"123",
                    "name":"product1",
                    "price":"123"
                },
                {
                    "id":"2",
                    "code":"234",
                    "name":"product2",
                    "price":"234"
                },
                {
                    "id":"3",
                    "code":"345",
                    "name":"product2",
                    "price":"234"
                }
            ]
        },
        {
            "id":"4",
            "name":"category4",
            "products":[
                {
                    "id":"1",
                    "code":"123",
                    "name":"product1",
                    "price":"123"
                },
                {
                    "id":"2",
                    "code":"234",
                    "name":"product2",
                    "price":"234"
                },
                {
                    "id":"3",
                    "code":"345",
                    "name":"product2",
                    "price":"234"
                }
            ]
        }
    ];
    products=[];
}